name: Publish Release to Pages and GitHub Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # 需要写权限来创建 GitHub Release
  pages: write
  id-token: write

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 同样需要 fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: python -m pip install --upgrade pip build wheel simple503 twine

    - name: Build package with release version
      run: python -m build

    - name: Generate PEP 503 repository for releases
      run: |
        simple503 --base-url "/aibit-pylibs/" dist gh-pages/

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: gh-pages/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*

    - name: Publish to PyPI (optional)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@v1.10.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}